- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
current status on this PR
```clojure
 aditya-trivedi   src    all ≢  ?2 ~3 -1    mpicc -c mpi_wrapper.c -o mpi_wrapper.o
 aditya-trivedi   src    all ≢  ?2 ~3 -1    mpif90 -c mpi_c_bindings.f90 mpi.f90
 aditya-trivedi   src    all ≢  ?2 ~3 -1    mpif90 mpi_c_bindings.o mpi_wrapper.o mpi.o allreduce.f90 -o all && ./all
Allreduce test completed with            0  errors.
 aditya-trivedi   src    all ≢  ?2 ~3 -1    conda activate lf
 aditya-trivedi   src    all ≢  ?2 ~3 -1    gcc -I$CONDA_PREFIX/include -c mpi_wrapper.c
 aditya-trivedi   src    all ≢  ?2 ~3 -1    gfortran -c mpi_c_bindings.f90 mpi.f90 
 aditya-trivedi   src    all ≢  ?2 ~3 -1    gfortran  -L$CONDA_PREFIX/lib -lmpi mpi_c_bindings.o …
```
> Handle Arrays too for MPI_Allreduce subroutine

- .github/workflows/CI.yml
- tests/run_tests.sh
Fixes https://github.com/gxyd/c_mpi/issues/17
> CI: run tests at CI

- tests/allreduce.f90
- tests/run_tests.sh
This is due to the fact that currently we only handle the real(8) arrays in MPI_AllReduce
Will make a PR to handle integer Array in a while and test it too (This PR is just to remove unwanted skip in the run_tests.sh script
> Fix DataType of sendbuf and recvbuf

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
- tests/init_1.f90
Towards
https://github.com/lfortran/lfortran/issues/6564#issuecomment-2711171814 and #21 
and mimicing https://github.com/gxyd/POT3D/pull/73
> Remove C-Wrapper for MPI_Init

- tests/run_tests.sh
this makes it clear with colors, which test is starting, which failed and which test passed
The output now looks something like below on my terminal:
> test: improve run_tests.sh script to be less verbose

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
This changes mandates to change the MPI_INTEGER value for which I have to edit some datatype checks in mpi_wrapper.c
Things would break i guess 
But this needs strong review before merging
Cc:-@gxyd
> Handle Integer type arrays for MPI_Allreduce

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
- tests/compute_pi.f90
Fixes https://github.com/gxyd/c_mpi/issues/44
> tests: add test program to compute pi using Monte Carlo method

- tests/pot3d/validate.sh
Towards: https://github.com/gxyd/c_mpi/issues/41
> CI: run POT3D validation with MPI rank 4 as well

- src/mpi.f90
This removes a minor warning when running tests with LFortran, the warning is:
```console
warning: Assuming implicit save attribute for variable declaration
--> ../src/mpi.f90:144:27
|
144 |         integer(c_int) :: argc = 0
|                           ^^^^^^^^ help: add explicit save attribute or parameter attribute or initialize in a separate statement
Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
which doesn't occur anymore.
> initialize in a separate line to avoid LFortran warning

- src/mpi_wrapper.c
- tests/ssend_1.f90
Address https://github.com/gxyd/c_mpi/pull/56#pullrequestreview-2728512304
> Fix: use correct helper function

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
- tests/bcast_1.f90
> Remove C-wrapper for MPI_BCAST

- src/mpi.f90
- src/mpi_c_bindings.f90
'get_c_datatype_from_fortran' and 'c_mpi_datatype_f2c' serve the same purpose
> remove duplicate function 'get_c_datatype_from_fortran'

- tests/run_tests.sh
With this enhancement we can do this 
```clojure
 aditya-trivedi   tests    script_enhance ≢    FC='gfortran' ./run_tests.sh bcast_1.f90 
Received argument(s). Will only compile/run: bcast_1.f90
Compiling bcast_1...
Running bcast_1 with 1 MPI ranks...
Rank=           0  received integer=           1
Test bcast_1 with 1 MPI ranks PASSED!
Running bcast_1 with 2 MPI ranks...
Rank=           0  received integer=           1
Rank=           1  received integer=           1
Test bcast_1 with 2 MPI ranks PASSED!
Running bcast_1 with 4 MPI ranks...
Rank=           0  received integer=           1
Rank=           2  received integer=           1
Rank=           1  received integer=           1
Rank=           3  received integer=           1
Test bcast_1 with 4 MPI ranks PASSED!
... …
```
> ENH: Add Functionality of running only one test file if specified

- .github/workflows/CI.yml
- tests/run_tests.sh
Added tests like: https://github.com/gxyd/c_mpi/pull/77 work with MPI without wrappers but don't work with our wrappers.
The CI check ensures that the added test program actually works as expected with and without our MPI wrappers in pretty much the same way.
> run MPI without wrappers for standalone tests

- .github/workflows/CI.yml
Testing with just OpenMPI isn't enough, we'll need to make sure that the added test program work both with Open MPI and MPICH as well.
I've seen program (see e.g.; below), which don't work with one of them:
e.g.;
```f90
program cart_shift_1
use mpi
implicit none
integer :: ierr, rank, size
integer :: dims(2), comm_cart
logical :: periods(2)
integer :: rank_source, rank_dest
integer :: coords(2)
call MPI_INIT(ierr)
call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierr)
call MPI_COMM_SIZE(MPI_COMM_WORLD, size, ierr)
dims(1) = 2          ! rows
dims(2) = size/2     ! columns
periods(1) = .false. ! non-periodic in x
periods(2) = .false. ! non-periodic in y
call MPI_CART_CREATE(MPI_COMM_WORLD, 2, dims, periods, .true., comm_cart, ierr)
print *, "rank: ", rank
if (comm_cart == MPI_COMM_NULL) then
if …
```
> run standalone tests without custom MPI wrappers with MPICH as well

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_wrapper.c
Towards: https://github.com/gxyd/c_mpi/issues/101
> use Fortran code for setting the datatype

- src/mpi.f90
- src/mpi_c_bindings.f90
- tests/comm_dup_1.f90
Towards: https://github.com/lfortran/fortran_mpi/issues/121
MPI_Comm_dup duplicates the existing communicator 'comm' with associated key values, topology information and error handlers
> feat: implement wrappers for MPI_Comm_dup

- src/mpi.f90
- src/mpi_c_bindings.f90
- tests/allgatherv_1.f90
Towards #121 
MPI_Allgatherv is similar to MPI_Gatherv, but instead of gathering data to a single root process, it gathers data to all processes in the communicator.
> Feat: Add Wrappers for MPI_AllGatherv

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_constants.c
- tests/reduce_max_op_01.f90
> Add New MPI_OP-> MPI_MAX

- src/mpi.f90
- src/mpi_c_bindings.f90
- tests/comm_group_1.f90
> FEAT: Implement Wrappers of MPI_COMM_GROUP, MPI_GROUP_SIZE and MPI_GROUP_FREE

- src/mpi.f90
- src/mpi_c_bindings.f90
- tests/comm_free_1.f90
> FEAT: Implment Wrappers of MPI_COMM_FREE

- src/mpi.f90
- src/mpi_c_bindings.f90
- src/mpi_constants.c
- tests/allreduce_lor.f90
> Add new MPI_Op -> MPI_LOR and Add wrappers for Logical datatype for MPI_Allreduce
